# Generated by Django 4.1.2 on 2022-10-27 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explicacao', models.CharField(max_length=255)),
                ('documentacao', models.CharField(max_length=25)),
                ('data', models.DateField()),
                ('provas', models.TextField()),
                ('locais_aplicacao_prova', models.TextField()),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('historia', models.TextField(blank=True)),
                ('localizacao_pais', models.CharField(max_length=20)),
                ('localizacao_cidade', models.CharField(max_length=20)),
                ('cultura', models.TextField()),
                ('taxa_aceitacao', models.DecimalField(decimal_places=2, max_digits=4)),
                ('oferece_bolsa', models.BooleanField()),
                ('descricao_bolsa', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteudo.application')),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
