# Generated by Django 4.1.2 on 2022-10-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=28)),
                ('lingua_oficial', models.CharField(max_length=50)),
                ('continente', models.CharField(max_length=12)),
            ],
        ),
    ]
