# Generated by Django 4.1.2 on 2022-10-28 01:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0002_pais'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pais',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='universidade',
            name='localizacao_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='conteudo.pais'),
        ),
    ]
