# Generated by Django 4.1.2 on 2022-10-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0004_rename_nome_pais_nome_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='continente',
            field=models.CharField(max_length=35),
        ),
    ]
