# Generated by Django 4.1.2 on 2022-10-29 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudo', '0008_alter_universidade_nome_universidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universidade_desejada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteudo.universidade')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
