# Generated by Django 4.1.2 on 2022-10-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0011_alter_collegelist_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='listaNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_news', models.CharField(max_length=255)),
            ],
        ),
    ]
