# Generated by Django 4.1.2 on 2022-11-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0015_alter_collegelist_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
