# Generated by Django 4.1.2 on 2022-11-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0016_delete_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universidade',
            old_name='application',
            new_name='descricao_application',
        ),
        migrations.AddField(
            model_name='universidade',
            name='data_application',
            field=models.DateField(blank=True, null=True),
        ),
    ]
